//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetroPayesh.Models.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataBase : DbContext
    {
        public DataBase()
            : base("name=DataBase")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Colors> Tbl_Colors { get; set; }
        public virtual DbSet<Tbl_Comments> Tbl_Comments { get; set; }
        public virtual DbSet<Tbl_ContactUs> Tbl_ContactUs { get; set; }
        public virtual DbSet<Tbl_Documents> Tbl_Documents { get; set; }
        public virtual DbSet<Tbl_Factor> Tbl_Factor { get; set; }
        public virtual DbSet<Tbl_FactorItems> Tbl_FactorItems { get; set; }
        public virtual DbSet<Tbl_Gallery> Tbl_Gallery { get; set; }
        public virtual DbSet<Tbl_ProductImages> Tbl_ProductImages { get; set; }
        public virtual DbSet<Tbl_Products> Tbl_Products { get; set; }
        public virtual DbSet<Tbl_Representations> Tbl_Representations { get; set; }
        public virtual DbSet<Tbl_Setting> Tbl_Setting { get; set; }
        public virtual DbSet<Tbl_ShoppingCart> Tbl_ShoppingCart { get; set; }
        public virtual DbSet<Tbl_Tag> Tbl_Tag { get; set; }
        public virtual DbSet<Tbl_TempColor> Tbl_TempColor { get; set; }
        public virtual DbSet<Tbl_Videos> Tbl_Videos { get; set; }
    }
}
