//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetroPayesh.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ShoppingCart
    {
        public int ID { get; set; }
        public int ProductID { get; set; }
        public int ProductColorID { get; set; }
        public int ProductCount { get; set; }
        public string UserIP { get; set; }
    }
}
