//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetroPayesh.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Comments
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Rate { get; set; }
        public int ProductID { get; set; }
        public System.DateTime CommentDate { get; set; }
        public string CommentTime { get; set; }
        public bool ReadStatus { get; set; }
        public bool ShowStatus { get; set; }
    }
}
