//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetroPayesh.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Products
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Price { get; set; }
        public string CatalogName { get; set; }
        public string MetaData_Description { get; set; }
        public string Additional_Description { get; set; }
        public string AndroidText { get; set; }
    }
}
